type Language = 'en' | 'es';

export const strings: Record<Language, Record<string, any>> = {
  en: {
    auth: {
      login: 'Log In',
      signup: 'Sign Up',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      google: 'Continue with Google',
      apple: 'Continue with Apple',
      loginButton: 'Log In',
      signupButton: 'Create Account',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      forgotPassword: 'Forgot password?',
      error: 'Error',
      subtitle: 'Detect deals before everyone else',
      or: 'or',
      referralCode: 'Referral code (optional)',
      toggleLogin: "Don't have an account? ",
      toggleSignup: 'Already have an account? ',
      apple: 'Sign in with Apple',
      appleES: 'Continuar con Apple',
    },
    common: {
      ok: 'OK',
      cancel: 'Cancel',
    },
    deals: {
      seeDeal: 'See deal',
      getDeal: 'Get Deal',
      whyThisDeal: 'Why this deal?',
      analyzingDeal: 'Analyzing deal…',
      unlockFlipAnalysis: 'Unlock flip analysis with Premium',
      flipPotential: 'Flip potential:',
      disclaimer: 'This deal is live and may sell out quickly. Pricing and availability can change at any time.',
    },
    explore: {
      title: 'Explore Deals',
      search: 'Search deals or stores...',
      premiumLocked: 'premium deals locked — Tap to unlock',
      free: 'Free',
      allDeals: 'All Deals',
      filter: 'Filter',
      hot: '🔥 Hot',
      rare: '💎 Rare',
      lightning: '⚡ Lightning',
      code: '🏷 Code',
      allStores: '🏬 All Stores',
    },
    radar: {
      scanning: 'SCANNING RADAR...',
      silence: 'RADAR SILENCE',
      noSignals: 'No signals on this frequency right now.',
      locationOn: 'Location ON',
      eliteFrequencies: '🔒 Elite Frequencies Locked',
      grab: 'GRAB',
      justIn: 'JUST IN',
    },
    flipit: {
      title: 'Flip It',
      urlPlaceholder: 'https://amazon.com/product...',
      namePlaceholder: 'Product name',
      pricePlaceholder: 'Buy price ($)',
      missingProduct: 'Missing product',
      enterProductName: 'Enter a product name.',
      missingPrice: 'Missing price',
      enterValidPrice: 'Enter a valid buy price.',
      invalidLink: 'Invalid link',
      invalidUrl: 'Paste a valid product URL (Amazon, Target, Home Depot, Walmart, etc.).',
      almostThere: 'Almost there',
      confirmBuyPrice: 'We got the product name — just confirm the buy price below, then Analyze.',
      enterDetails: 'Enter details',
      couldntReadLink: 'Couldn\'t read that link — enter the product name and price below.',
      working: 'Working…',
      evaluateDeal: 'Evaluate Deal',
      enterManually: 'or enter manually →',
      analyzeFlip: 'Analyze Flip',
      pasteLink: 'Paste Product Link',
      performance: 'Your Flip Performance',
      condNew: 'New',
      condLikeNew: 'Like New',
      condUsedGood: 'Used - Good',
      condUsedFair: 'Used - Fair',
      scanBarcode: 'Scan Barcode',
      checkResale: 'Check resale value',
      myFlips: 'My Flips',
      liveSavedFlips: 'Live saved flips',
      totalFlips: 'Total Flips',
      totalProfit: 'Total Profit',
    },
    creator: {
      title: 'Creator Hub',
      unlock: 'Unlock the Creator dashboard to earn commissions, share your referral link, climb creator tiers, and request payouts.',
      unlockBtn: 'Unlock Creator (Premium)',
      welcome: 'Welcome back',
      earned: 'Earned',
      referrals: 'referrals',
      more: 'more',
      unlocks: 'unlocks',
      maxTier: 'Max tier reached — you\'re an Elite Creator!',
      clicks: 'Clicks',
      conversion: 'Conversion',
      campaigns: 'Campaigns',
      referralLink: 'Your Referral Link',
      copy: 'Copy',
      share: 'Share',
      earningsPayouts: 'Earnings & Payouts',
      lifetime: 'Lifetime',
      pending: 'Pending',
      requestPayout: 'Request Payout',
      moreToUnlock: 'more to unlock',
      yourCampaigns: 'Your Campaigns',
      noCampaigns: 'No campaigns yet.',
      createFirst: 'Create your first campaign to start tracking performance.',
      promoTools: 'Promo Tools',
      shareTiktok: 'Share to TikTok',
      shareInstagram: 'Share to Instagram',
      shareTwitter: 'Share to X / Twitter',
      shareAnywhere: 'Share Anywhere',
      bronze: 'Bronze Creator',
      silver: 'Silver Creator',
      gold: 'Gold Creator',
      platinum: 'Platinum Creator',
      elite: 'Elite Creator',
      referrals: 'referrals',
      referral: 'referral',
      dashboardAccess: 'Creator dashboard access',
      fasterPayouts: 'Faster payouts',
      higherCommission: 'Higher commission rate',
      prioritySupport: 'Priority support + bonuses',
      topCommission: 'Top commission + early campaigns',
      bronzePerk: 'Creator dashboard access',
      silverPerk: 'Faster payouts',
      goldPerk: 'Higher commission rate',
      platinumPerk: 'Priority support + bonuses',
      elitePerk: 'Top commission + early campaigns',
      unlocks: 'unlocks',
    },
  },
  es: {
    auth: {
      login: 'Iniciar Sesión',
      signup: 'Crear Cuenta',
      email: 'Correo',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      google: 'Continuar con Google',
      apple: 'Continuar con Apple',
      loginButton: 'Iniciar Sesión',
      signupButton: 'Crear Cuenta',
      noAccount: '¿No tienes cuenta?',
      haveAccount: '¿Ya tienes cuenta?',
      forgotPassword: '¿Olvidaste tu contraseña?',
      error: 'Error',
      subtitle: 'Detecta ofertas antes que todos',
      or: 'o',
      referralCode: 'Código de referencia (opcional)',
      toggleLogin: '¿No tienes cuenta? ',
      toggleSignup: '¿Ya tienes cuenta? ',
      apple: 'Continuar con Apple',
      appleES: 'Continuar con Apple',
    },
    common: {
      ok: 'OK',
      cancel: 'Cancelar',
    },
    deals: {
      seeDeal: 'Ver oferta',
      getDeal: 'Obtener oferta',
      whyThisDeal: '¿Por qué esta oferta?',
      analyzingDeal: 'Analizando oferta…',
      unlockFlipAnalysis: 'Desbloquea análisis de volteador con Premium',
      flipPotential: 'Potencial de volteador:',
      disclaimer: 'Esta oferta está activa y puede agotarse rápidamente. El precio y la disponibilidad pueden cambiar en cualquier momento.',
    },
    explore: {
      title: 'Explorar Ofertas',
      search: 'Buscar ofertas o tiendas...',
      premiumLocked: 'ofertas premium bloqueadas — Toca para desbloquear',
      free: 'Gratis',
      allDeals: 'Todas las ofertas',
      filter: 'Filtro',
      hot: '🔥 Popular',
      rare: '💎 Raro',
      lightning: '⚡ Relámpago',
      code: '🏷 Código',
      allStores: '🏬 Todas las tiendas',
    },
    radar: {
      scanning: 'ESCANEANDO RADAR...',
      silence: 'SILENCIO DE RADAR',
      noSignals: 'Sin señales en esta frecuencia ahora mismo.',
      locationOn: 'Ubicación ACTIVADA',
      eliteFrequencies: '🔒 Frecuencias Élite Bloqueadas',
      grab: 'AGARRAR',
      justIn: 'RECIÉN LLEGADO',
    },
    flipit: {
      title: 'Volteador',
      urlPlaceholder: 'https://amazon.com/product...',
      namePlaceholder: 'Nombre del producto',
      pricePlaceholder: 'Precio de compra ($)',
      missingProduct: 'Producto faltante',
      enterProductName: 'Ingresa un nombre de producto.',
      missingPrice: 'Precio faltante',
      enterValidPrice: 'Ingresa un precio de compra válido.',
      invalidLink: 'Enlace inválido',
      invalidUrl: 'Pega una URL de producto válida (Amazon, Target, Home Depot, Walmart, etc.).',
      almostThere: 'Casi listo',
      confirmBuyPrice: 'Tenemos el nombre del producto — solo confirma el precio de compra a continuación y luego Analiza.',
      enterDetails: 'Ingresa detalles',
      couldntReadLink: 'No pudimos leer ese enlace — ingresa el nombre del producto y el precio a continuación.',
      working: 'Trabajando…',
      evaluateDeal: 'Evaluar oferta',
      enterManually: 'o ingresa manualmente →',
      analyzeFlip: 'Analizar volteador',
      pasteLink: 'Pega enlace de producto',
      performance: 'Tu rendimiento en operaciones de compraventa rápida (flips)',
      condNew: 'Nuevo',
      condLikeNew: 'Como nuevo',
      condUsedGood: 'Usado - Bueno',
      condUsedFair: 'Usado - Regular',
      scanBarcode: 'Escanear código de barras',
      checkResale: 'Verificar valor de reventa',
      myFlips: 'Mis Reventas',
      liveSavedFlips: 'Reventas Guardadas',
      evaluateDeal: 'Evaluar oferta',
      analyzeFlip: 'Analizar volteo',
      totalFlips: 'Total de operaciones',
      totalProfit: 'Total de ganancias',
    },
    creator: {
      title: 'Centro de Creadores',
      unlock: 'Desbloquea el panel de creadores para ganar comisiones, compartir tu enlace de referencia, escalar niveles de creador y solicitar pagos.',
      unlockBtn: 'Desbloquear Creador (Premium)',
      welcome: 'Bienvenido de vuelta',
      earned: 'Ganado',
      referrals: 'referidos',
      more: 'más',
      unlocks: 'desbloquea',
      maxTier: '¡Nivel máximo alcanzado — eres un Creador Élite!',
      clicks: 'Clics',
      conversion: 'Conversión',
      campaigns: 'Campañas',
      referralLink: 'Tu Enlace de Referencia',
      copy: 'Copiar',
      share: 'Compartir',
      earningsPayouts: 'Ganancias y Pagos',
      lifetime: 'Histórico',
      pending: 'Pendiente',
      requestPayout: 'Solicitar Pago',
      moreToUnlock: 'más para desbloquear',
      yourCampaigns: 'Tus Campañas',
      noCampaigns: 'Sin campañas aún.',
      createFirst: 'Crea tu primera campaña para comenzar a rastrear el desempeño.',
      promoTools: 'Herramientas de Promoción',
      shareTiktok: 'Compartir en TikTok',
      shareInstagram: 'Compartir en Instagram',
      shareTwitter: 'Compartir en X / Twitter',
      shareAnywhere: 'Compartir en cualquier lugar',
      bronze: 'Creador Bronce',
      silver: 'Creador Plata',
      gold: 'Creador Oro',
      platinum: 'Creador Platino',
      elite: 'Creador Élite',
      referrals: 'referidos',
      referral: 'referido',
      dashboardAccess: 'Acceso al panel de creadores',
      fasterPayouts: 'Pagos más rápidos',
      higherCommission: 'Tasa de comisión más alta',
      prioritySupport: 'Soporte prioritario + bonificaciones',
      topCommission: 'Comisión superior + campañas tempranas',
      bronzePerk: 'Acceso al panel de creadores',
      silverPerk: 'Pagos más rápidos',
      goldPerk: 'Tasa de comisión más alta',
      platinumPerk: 'Soporte prioritario + bonificaciones',
      elitePerk: 'Comisión superior + campañas tempranas',
      unlocks: 'desbloquea',
    },
  },
};

export function getStrings(language: Language) {
  return strings[language] || strings.en;
}
