type Language = 'en' | 'es';

export const strings: Record<Language, Record<string, any>> = {
  en: {
    auth: {
      login: 'Log In',
      signup: 'Sign Up',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      google: 'Continue with Google',
      apple: 'Continue with Apple',
      loginButton: 'Log In',
      signupButton: 'Create Account',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      forgotPassword: 'Forgot password?',
      error: 'Error',
      subtitle: 'Detect deals before everyone else',
      or: 'or',
      referralCode: 'Referral code (optional)',
      toggleLogin: "Don't have an account? ",
      toggleSignup: 'Already have an account? ',
      apple: 'Sign in with Apple',
      appleES: 'Continuar con Apple',
    },
    common: {
      ok: 'OK',
      cancel: 'Cancel',
    },
    deals: {
      seeDeal: 'See deal',
      getDeal: 'Get Deal',
      whyThisDeal: 'Why this deal?',
      analyzingDeal: 'Analyzing deal…',
      unlockFlipAnalysis: 'Unlock flip analysis with Premium',
      flipPotential: 'Flip potential:',
      disclaimer: 'This deal is live and may sell out quickly. Pricing and availability can change at any time.',
    },
    explore: {
      title: 'Explore Deals',
      search: 'Search deals or stores...',
      premiumLocked: 'premium deals locked — Tap to unlock',
      free: 'Free',
      allDeals: 'All Deals',
      filter: 'Filter',
      hot: '🔥 Hot',
      rare: '💎 Rare',
      lightning: '⚡ Lightning',
      code: '🏷 Code',
      allStores: '🏬 All Stores',
    },
  },
  es: {
    auth: {
      login: 'Iniciar Sesión',
      signup: 'Crear Cuenta',
      email: 'Correo',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      google: 'Continuar con Google',
      apple: 'Continuar con Apple',
      loginButton: 'Iniciar Sesión',
      signupButton: 'Crear Cuenta',
      noAccount: '¿No tienes cuenta?',
      haveAccount: '¿Ya tienes cuenta?',
      forgotPassword: '¿Olvidaste tu contraseña?',
      error: 'Error',
      subtitle: 'Detecta ofertas antes que todos',
      or: 'o',
      referralCode: 'Código de referencia (opcional)',
      toggleLogin: '¿No tienes cuenta? ',
      toggleSignup: '¿Ya tienes cuenta? ',
      apple: 'Continuar con Apple',
      appleES: 'Continuar con Apple',
    },
    common: {
      ok: 'OK',
      cancel: 'Cancelar',
    },
    deals: {
      seeDeal: 'Ver oferta',
      getDeal: 'Obtener oferta',
      whyThisDeal: '¿Por qué esta oferta?',
      analyzingDeal: 'Analizando oferta…',
      unlockFlipAnalysis: 'Desbloquea análisis de volteador con Premium',
      flipPotential: 'Potencial de volteador:',
      disclaimer: 'Esta oferta está activa y puede agotarse rápidamente. El precio y la disponibilidad pueden cambiar en cualquier momento.',
    },
    explore: {
      title: 'Explorar Ofertas',
      search: 'Buscar ofertas o tiendas...',
      premiumLocked: 'ofertas premium bloqueadas — Toca para desbloquear',
      free: 'Gratis',
      allDeals: 'Todas las ofertas',
      filter: 'Filtro',
      hot: '🔥 Popular',
      rare: '💎 Raro',
      lightning: '⚡ Relámpago',
      code: '🏷 Código',
      allStores: '🏬 Todas las tiendas',
    },
  },
};

export function getStrings(language: Language) {
  return strings[language] || strings.en;
}
